services:
  - type: worker
    name: kolomna-bot
    runtime: docker
    plan: free
    startCommand: python main.py
    envVars:
      - key: CITIZEN_BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: ADMIN_GROUP_CHAT_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
